AAdded project relaed files
dmnglore/githubdemo pull request #1
Opened 2024-09-22 23:35 UTC by dmnglore

AAdded project relaed files

2024-09-22 23:59 UTC, sadhanmb requested changes
please validate all review comments and take actions accordingly

2024-09-22 23:59 UTC, sadhanmb commented on mvnw
delete codeowners.txt which is a unused file

2024-09-22 23:59 UTC, sadhanmb commented on src/test/java/com/craftdmo/githubdemo/GithubdemoApplicationTests.java
Add more tests for the scenarios

2024-09-22 23:59 UTC, sadhanmb commented on src/main/resources/application.properties
provide unique port number since 8080 might be used by some other application

2024-09-23 00:12 UTC, dmnglore commented
> please validate all review comments and take actions accordingly

Fixed

2024-09-23 00:12 UTC, dmnglore commented
fxed

2024-09-23 00:12 UTC, dmnglore commented on mvnw
fixed

2024-09-23 00:12 UTC, dmnglore commented
addressed all review commens

2024-09-24 23:10 UTC, dmnglore commented on mvnw
fixed

2024-09-24 23:11 UTC, dmnglore commented on src/test/java/com/craftdmo/githubdemo/GithubdemoApplicationTests.java
added

2024-09-24 23:20 UTC, merged

2024-09-24 23:20 UTC, dmnglore commented
merged all changes